#ifndef __API_MESSAGEMANAGERKEYBOARDCODES_H__
#define __API_MESSAGEMANAGERKEYBOARDCODES_H__

#define MeM_KEY_NOKEY 0
#define MeM_KEY_TAB 8
#define MeM_KEY_BACKSPACE 9
#define MeM_KEY_ENTER 13
#define MeM_KEY_ESC 27
#define MeM_KEY_LSHIFT 128
#define MeM_KEY_RSHIFT 129
#define MeM_KEY_LCTRL 130
#define MeM_KEY_RCTRL 131
#define MeM_KEY_ALT 132
#define MeM_KEY_ALTGR 133
#define MeM_KEY_LEFTWINDOWS 134
#define MeM_KEY_RIGHTWINDOWS 135
#define MeM_KEY_MENUPOPUP 136
#define MeM_KEY_ESCAPE 137
#define MeM_KEY_KEYPAD_HOME 200
#define MeM_KEY_KEYPAD_UP 201
#define MeM_KEY_KEYPAD_PGUP 201
#define MeM_KEY_KEYPAD_LEFT 202
#define MeM_KEY_KEYPAD_CENTRE 203
#define MeM_KEY_KEYPAD_RIGHT 204
#define MeM_KEY_KEYPAD_END 205
#define MeM_KEY_KEYPAD_DOWN 206
#define MeM_KEY_KEYPAD_PGDN 207
#define MeM_KEY_KEYPAD_INS 208
#define MeM_KEY_KEYPAD_DEL 209

#endif // __API_MESSAGEMANAGERKEYBOARDCODES_H__

