#ifndef __API_OBJECTMANAGER_H__
#define __API_OBJECTMANAGER_H__

#include <API/Types.h>

#define OM_NAMELENGTH 48
#define OM_MAXKEYSTRINGSIZE 4096

enum {
    OM_ENTITY,
    OM_PROCESS,
    OM_THREAD,
    OM_MODULEHANDLE,
    OM_MODULE,
    OM_MODULECALL,
    OM_MESSAGEPORT,
    OM_MESSAGE,
    OM_DEVICE,
    OM_DEVICERESOURCE,
    OM_IODEVICE,
    OM_FILESYSTEM,
    OM_VOLUME,
    OM_FILEHANDLE
};

// Error messages
#define OM_OBJECTNOTFOUND 0xFFFFFFFF
#define OM_PATHTOOLONG 0xFFFFFFFE
#define OM_KEYTOOLONG 0xFFFFFFFD

#endif // __API_OBJECTMANAGER_H__
