[package]
name = "voxel-tracer"
version = "0.1.0"
authors = ["Daryl Dudey <daryljdudey@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.33.0"