#ifndef __K_KMESSAGES_KEYBOARD_H__
#define __K_KMESSAGES_KEYBOARD_H__

#define KMESSAGE_KEY_NOKEY 0
#define KMESSAGE_KEY_TAB 8
#define KMESSAGE_KEY_BACKSPACE 9
#define KMESSAGE_KEY_ENTER 13
#define KMESSAGE_KEY_ESC 27
#define KMESSAGE_KEY_LSHIFT 128
#define KMESSAGE_KEY_RSHIFT 129
#define KMESSAGE_KEY_LCTRL 130
#define KMESSAGE_KEY_RCTRL 131
#define KMESSAGE_KEY_ALT 132
#define KMESSAGE_KEY_ALTGR 133
#define KMESSAGE_KEY_LEFTWINDOWS 134
#define KMESSAGE_KEY_RIGHTWINDOWS 135
#define KMESSAGE_KEY_MENUPOPUP 136
#define KMESSAGE_KEY_ESCAPE 137
#define KMESSAGE_KEY_KEYPAD_HOME 200
#define KMESSAGE_KEY_KEYPAD_UP 201
#define KMESSAGE_KEY_KEYPAD_PGUP 201
#define KMESSAGE_KEY_KEYPAD_LEFT 202
#define KMESSAGE_KEY_KEYPAD_CENTRE 203
#define KMESSAGE_KEY_KEYPAD_RIGHT 204
#define KMESSAGE_KEY_KEYPAD_END 205
#define KMESSAGE_KEY_KEYPAD_DOWN 206
#define KMESSAGE_KEY_KEYPAD_PGDN 207
#define KMESSAGE_KEY_KEYPAD_INS 208
#define KMESSAGE_KEY_KEYPAD_DEL 209

#endif // __K_KMESSAGES_KEYBOARD_H__

