[package]
name = "project_euler"
version = "0.1.0"
authors = ["Daryl Dudey <daryljdudey@googlemail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
num = { version = "0.2.1", features = ["rand"] }