uchar g_nKeyCodes[ 128 ] = {
                               MeM_KEY_NOKEY,
                               MeM_KEY_ESCAPE,
                               '1',
                               '2',
                               '3',
                               '4',
                               '5',
                               '6',
                               '7',
                               '8',
                               '9',                                                                                                                                                                                                                                     	    // 10
                               '0',
                               '-',
                               '=',
                               MeM_KEY_BACKSPACE,
                               MeM_KEY_TAB,
                               'q',
                               'w',
                               'e',
                               'r',
                               't',                                                                                                                                                                                                                                     	  // 20
                               'y',
                               'u',
                               'i',
                               'o',
                               'p',
                               '[',
                               ']',
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               'a',                                                                                                                                                                                                                                     	       // 30
                               's',
                               'd',
                               'f',
                               'g',
                               'h',
                               'j',
                               'k',
                               'l',
                               ';',
                               '\'',                                                                                                                                                                                                                                     	       // 40
                               MeM_KEY_ENTER,
                               MeM_KEY_LSHIFT,
                               '#',
                               'z',
                               'x',
                               'c',
                               'v',
                               'b',
                               'n',
                               'm',                                                                                                                                                                                                                                     	     // 50
                               ',',
                               '.',
                               '/',
                               MeM_KEY_RSHIFT,
                               '*',
                               MeM_KEY_LCTRL,
                               ' ',
                               MeM_KEY_ALT,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,                                                                                                                                                                                                                                      // 60
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,                                                                                                                                                                                                                                      // 70
                               MeM_KEY_KEYPAD_HOME,
                               MeM_KEY_KEYPAD_UP,
                               MeM_KEY_KEYPAD_PGUP,
                               '-',
                               MeM_KEY_KEYPAD_LEFT,
                               MeM_KEY_KEYPAD_CENTRE,
                               MeM_KEY_KEYPAD_RIGHT,
                               '+',
                               MeM_KEY_KEYPAD_END,
                               MeM_KEY_KEYPAD_DOWN,                                                                                                                                                                                                                                      // 80
                               MeM_KEY_KEYPAD_PGDN,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               '\\',
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,                                                                                                                                                                                                                                         // 90
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,                                                                                                                                                                                                                                         // 100
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,                                                                                                                                                                                                                                         // 110
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,                                                                                                                                                                                                                                         // 120
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY,
                               MeM_KEY_NOKEY
                           };

uchar g_nKeyCodesShift[ 128 ] = {
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_ESCAPE,
                                    '!',
                                    '"',
                                    '£',
                                    '$',
                                    '%',
                                    '^',
                                    '&',
                                    '*',
                                    '(',
                                    ')',                                                                                                                                                                                                                                     	    // 10
                                    '_',
                                    '+',
                                    MeM_KEY_BACKSPACE,
                                    MeM_KEY_TAB,
                                    'Q',
                                    'W',
                                    'E',
                                    'R',
                                    'T',                                                                                                                                                                                                                                     	  // 20
                                    'Y',
                                    'U',
                                    'I',
                                    'O',
                                    'P',
                                    '{',
                                    '}',
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    'A',                                                                                                                                                                                                                                     	       // 30
                                    'S',
                                    'D',
                                    'F',
                                    'G',
                                    'H',
                                    'J',
                                    'K',
                                    'L',
                                    ':',
                                    '@',                                                                                                                                                                                                                                     	       // 40
                                    MeM_KEY_ENTER,
                                    MeM_KEY_LSHIFT,
                                    '~',
                                    'Z',
                                    'X',
                                    'C',
                                    'V',
                                    'B',
                                    'N',
                                    'M',                                                                                                                                                                                                                                     	     // 50
                                    '<',
                                    '>',
                                    '?',
                                    MeM_KEY_RSHIFT,
                                    '*',
                                    MeM_KEY_LCTRL,
                                    ' ',
                                    MeM_KEY_ALT,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,                                                                                                                                                                                                                                      // 60
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,                                                                                                                                                                                                                                      // 70
                                    MeM_KEY_KEYPAD_HOME,
                                    MeM_KEY_KEYPAD_UP,
                                    MeM_KEY_KEYPAD_PGUP,
                                    '-',
                                    MeM_KEY_KEYPAD_LEFT,
                                    MeM_KEY_KEYPAD_CENTRE,
                                    MeM_KEY_KEYPAD_RIGHT,
                                    '+',
                                    MeM_KEY_KEYPAD_END,
                                    MeM_KEY_KEYPAD_DOWN,                                                                                                                                                                                                                                      // 80
                                    MeM_KEY_KEYPAD_PGDN,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    '|',
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,                                                                                                                                                                                                                                         // 90
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,                                                                                                                                                                                                                                         // 100
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,                                                                                                                                                                                                                                         // 110
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,                                                                                                                                                                                                                                         // 120
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY,
                                    MeM_KEY_NOKEY
                                };


