[package]
name = 'bios'
version = '0.1.0'
authors = ['Daryl Dudey <daryljdudey@googlemail.com>']
edition = '2018'

[features]
lcd-green = []
lcd-grey = []
default = ['lcd-grey']

[dependencies]
ggez = '0.5.1'
rand = '0.7.3'
