[package]
name = "little_people"
version = "0.1.0"
authors = ["Daryl Dudey <daryljdudey@googlemail.com>"]
edition = "2018"

[dependencies]
specs = { version = "0.16.1", features = ["specs-derive"] }
ggez = "0.5.1"
rand = "0.7.3"