// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Entity = (function() {
    function Entity(layer) {
      this.modules = [];
      this.group = new Kinetic.Group;
      layer.add(this.group);
    }

    Entity.prototype.addmodule = function(m, x, y) {
      m.setPosition(x, y);
      return this.modules.push(m);
    };

    Entity.prototype.setPosition = function(x, y) {
      return this.group.setAbsolutePosition(x, y);
    };

    Entity.prototype.setRotation = function(r) {
      return this.group.setRotationDeg(r);
    };

    Entity.prototype.rotate = function(r) {
      return this.group.rotateDeg(r);
    };

    Entity.prototype.move = function(x, y) {
      return this.group.move(x, y);
    };

    return Entity;

  })();

  window.EntityFighter = (function(_super) {
    __extends(EntityFighter, _super);

    function EntityFighter(layer) {
      var m;
      EntityFighter.__super__.constructor.call(this, layer);
      m = new window.ModuleFighter(this.group);
      this.addmodule(m, 0, 0);
    }

    return EntityFighter;

  })(window.Entity);

}).call(this);
