// Generated by CoffeeScript 1.6.3
(function() {
  var update;

  window.start = function() {
    var f, x, _i;
    this.graphics = new window.Graphics;
    this.graphics.grid();
    this.layer = new Kinetic.Layer;
    this.graphics.addToStage(this.layer);
    this.fighters = [];
    for (x = _i = 0; _i <= 1000; x = ++_i) {
      f = new window.EntityFighter(this.layer);
      f.setPosition(Math.random() * this.graphics.stage.getAttr('width'), Math.random() * this.graphics.stage.getAttr('height'));
      f.setRotation(Math.random() * 360.0);
      this.fighters.push(f);
    }
    return setInterval(update, 25);
  };

  update = function() {
    var f, _i, _len, _ref;
    _ref = this.fighters;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      f = _ref[_i];
      f.move(Math.random() * 2.0 - 1.0, Math.random() * 2.0 - 1.0);
      f.rotate(Math.random() * 5.0);
    }
    return this.layer.draw();
  };

}).call(this);
