// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Module = (function() {
    function Module() {
      this.points = [0, 0];
    }

    Module.prototype.build = function(group) {
      this.line = new Kinetic.Line({
        points: this.points,
        stroke: 'red',
        strokewidth: 1.5,
        opacity: 1,
        lineJoin: 'round',
        lineCap: 'round'
      });
      return group.add(this.line);
    };

    Module.prototype.setPosition = function(x, y) {
      return this.line.setAbsolutePosition(x, y);
    };

    return Module;

  })();

  window.ModuleFighter = (function(_super) {
    __extends(ModuleFighter, _super);

    function ModuleFighter(group) {
      this.points = [-5, -5, 0, 5, 5, -5, -5, -5];
      this.build(group);
    }

    return ModuleFighter;

  })(window.Module);

}).call(this);
